registrator:
  restart: always
  image: myena/aardvark:latest
  command: -asn 65123 -network weave,my-awesome-network -peer bgp01.domain.tld,bgp02.domain.tld
  net: "host"
  volumes:
    -  /var/run/docker.sock:/tmp/docker.sock
