registrator:
  restart: always
  image: myena/aardvark:latest
  command: -asn 65000 -network weave,my-awesome-network -peer rt-reflector-01.domain.tld,rt-reflector-02.domain.tld
  net: "host"
  volumes:
    -  /var/run/docker.sock:/tmp/docker.sock
